#!/usr/bin/env python3
# tab-width:4

from __future__ import annotations

# Auto-generated by generate_color_palettes.py
# Names ending in '_r' are reversed variants.

COLOR_PALETTES = {
    "Perceptually Uniform": [
        "cividis",
        "cividis_r",
        "plasma",
        "plasma_r",
        "viridis",
        "viridis_r",
    ],
    "Sequential": [
        "autumn",
        "autumn_r",
        "cool",
        "cool_r",
        "turbo",
        "turbo_r",
    ],
    "Diverging": [
        "RdYlBu",
        "RdYlBu_r",
    ],
    "Cyclic": [
        "hsv",
        "hsv_r",
        "twilight",
        "twilight_r",
    ],
    "Miscellaneous": [
        "brg",
        "brg_r",
        "gist_ncar",
        "gist_ncar_r",
        "gist_rainbow",
        "gist_rainbow_r",
        "jet",
        "jet_r",
        "nipy_spectral",
        "nipy_spectral_r",
    ],
}
